---
name: Clojure
on: [push]
jobs:
  build:
    permissions: write-all
    name: Lint source code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.12.0.1456
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: clojure -X:test
