---
name: Clojure
on: [push]
jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@12.5

      - name: Run tests
        run: clojure -X:test
